In [1]:
import theano

In [3]:
import statsmodels.api as sm

In [4]:
import sklearn.datasets as datasets

In [5]:
import keras

Using TensorFlow backend.


In [6]:
from keras.models import Sequential

In [7]:
from keras.layers.core import Dense, Activation, Dropout, Flatten

In [8]:
import pandas as pd

In [9]:
from matplotlib import pyplot as plt

In [10]:
import sklearn.datasets
from sklearn import datasets

In [11]:
from keras.layers.convolutional import Convolution2D, MaxPooling2D

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
from sklearn.decomposition import PCA

In [14]:
from sklearn.cluster import KMeans

In [15]:
from sklearn.metrics import silhouette_score, adjusted_rand_score

In [16]:
from sklearn import metrics

In [17]:
import sklearn

In [18]:
from sklearn.datasets import fetch_mldata

In [37]:
dataDict=datasets.fetch_openml('mnist_784', version=1)

In [38]:
x=dataDict['data']

In [39]:
y=dataDict['target']

In [108]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=.1)

In [109]:
x_train.shape[1]


784

In [110]:
x_train=x_train.reshape((63000, 1, 28, 28))


In [111]:
x_test=x_test.reshape((7000, 1, 28, 28))

In [112]:
y_train=pd.get_dummies(y_train).as_matrix()
y_train.shape

/Users/tatsianasokalava/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


(63000, 10)

In [113]:
#Convolution layers expect a 4-D input so we reshape our 2-D input

In [114]:
nb_sample=x_train.shape[0]
nb_sample

63000

In [115]:
nb_classes=y_train.shape[1]
nb_classes

10

In [116]:
# Lets set some hyperparameters
batch_size=16
kernel_width=5
kernel_height=5
stride=1
n_filters=10

In [117]:
#Let's fit the model
model=Sequential()


In [118]:
model.add(Convolution2D(nb_filter=n_filters, input_shape=(1,28,28), nb_row=kernel_height, nb_col=kernel_width, subsample=(stride, stride),data_format='channels_first'))

/Users/tatsianasokalava/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(input_shape=(1, 28, 28..., data_format="channels_first", kernel_size=(5, 5), filters=10, strides=(1, 1))`
  """Entry point for launching an IPython kernel.


In [119]:
model.add(Activation('relu'))

In [120]:
model.add(MaxPooling2D(pool_size=(5,5)))

In [121]:
model.add(Dropout(0.5))

In [122]:
model.add(Flatten())

In [123]:
model.add(Dense(nb_classes))

In [124]:
model.add(Activation('softmax'))

In [125]:
model.compile(loss='categorical_crossentropy', optimizer='adadelta')

In [126]:
print('fitting model')

fitting model


In [127]:
model.fit(x_train, y_train, nb_epoch=10)

/Users/tatsianasokalava/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.



Epoch 1/10
63000/63000 [==============================] - 23s 367us/step - loss: 3.6970
Epoch 2/10
63000/63000 [==============================] - 23s 360us/step - loss: 0.6379
Epoch 3/10
63000/63000 [==============================] - 23s 366us/step - loss: 0.5216
Epoch 4/10
63000/63000 [==============================] - 23s 366us/step - loss: 0.4713
Epoch 5/10
63000/63000 [==============================] - 23s 369us/step - loss: 0.4497
Epoch 6/10
63000/63000 [==============================] - 23s 368us/step - loss: 0.4400
Epoch 7/10
63000/63000 [==============================] - 23s 369us/step - loss: 0.4474
Epoch 8/10
63000/63000 [==============================] - 23s 369us/step - loss: 0.4335
Epoch 9/10
63000/63000 [==============================] - 23s 370us/step - loss: 0.4370
Epoch 10/10
63000/63000 [==============================] - 23s 372us/step - loss: 0.4377


In [133]:
probs=model.predict_proba(x_test)
probs

array([[2.7445995e-10, 3.7110532e-12, 4.9213418e-03, ..., 9.9186653e-01,
        2.5309168e-04, 1.8130880e-09],
       [2.6029474e-04, 8.4469830e-06, 5.5388544e-02, ..., 6.0612619e-01,
        3.2641226e-01, 9.5662260e-03],
       [1.4732285e-10, 1.1789479e-14, 9.2587597e-06, ..., 1.7051835e-04,
        1.6001915e-05, 9.9914837e-01],
       ...,
       [1.9967118e-07, 3.2231135e-06, 3.8278231e-04, ..., 1.0568178e-02,
        6.2055346e-03, 9.1663420e-01],
       [3.1021438e-03, 4.2359356e-09, 2.3635068e-05, ..., 4.6315175e-03,
        2.6539708e-03, 9.1083479e-01],
       [1.2303517e-05, 9.9006993e-01, 3.4978199e-05, ..., 2.0397897e-03,
        1.5542961e-03, 2.7563001e-03]], dtype=float32)

In [134]:
preds=model.predict(x_test)
preds

array([[2.7445995e-10, 3.7110532e-12, 4.9213418e-03, ..., 9.9186653e-01,
        2.5309168e-04, 1.8130880e-09],
       [2.6029474e-04, 8.4469830e-06, 5.5388544e-02, ..., 6.0612619e-01,
        3.2641226e-01, 9.5662260e-03],
       [1.4732285e-10, 1.1789479e-14, 9.2587597e-06, ..., 1.7051835e-04,
        1.6001915e-05, 9.9914837e-01],
       ...,
       [1.9967118e-07, 3.2231135e-06, 3.8278231e-04, ..., 1.0568178e-02,
        6.2055346e-03, 9.1663420e-01],
       [3.1021438e-03, 4.2359356e-09, 2.3635068e-05, ..., 4.6315175e-03,
        2.6539708e-03, 9.1083479e-01],
       [1.2303517e-05, 9.9006993e-01, 3.4978199e-05, ..., 2.0397897e-03,
        1.5542961e-03, 2.7563001e-03]], dtype=float32)

In [147]:
pred_classes=model.predict_classes(x_test)
pred_classes[1]

7

In [151]:
true_classes=pd.Series(y_test)
true_classes=true_classes.astype(int)


In [157]:
(pred_classes==true_classes).sum()

6550

In [156]:
(pred_classes==true_classes).sum()/y_test.shape

array([0.93571429])

In [158]:
y_test

array(['7', '7', '9', ..., '9', '9', '1'], dtype=object)